services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowix-api
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - redis
    networks:
      - apps-network

  redis:
    image: redis:7.2
    container_name: flowix-redis
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - apps-network

networks:
  apps-network:
    external: true