import "dotenv/config";
import mongoose from "mongoose";
import { NodeDefinition } from "../models/NodeDefinition";
import { NodeDataType } from "../types/NodeDataType";

const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/flowix";

const seedNodeDefinitions = [
  {
    name: "No Operation",
    fnKey: "noop",
    category: "utility",
    version: 1,
    scope: "workflow",
    inputs: [],
    outputs: [{ key: "result", type: NodeDataType.STRING, description: "Execution confirmation" }],
  },
  {
    name: "Delay",
    fnKey: "delay",
    category: "utility",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "delay",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1000,
        description: "Delay in milliseconds",
      },
    ],
    outputs: [
      { key: "delayed", type: NodeDataType.BOOLEAN, description: "Whether the delay was applied" },
      { key: "delayMs", type: NodeDataType.NUMBER, description: "Actual delay in milliseconds" },
    ],
  },
  {
    name: "Random Number",
    fnKey: "random.number",
    category: "utility",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "min",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0,
        description: "Valor mínimo del rango",
      },
      {
        key: "max",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Valor máximo del rango",
      },
      {
        key: "integer",
        type: NodeDataType.BOOLEAN,
        input: "select",
        options: ["true", "false"],
        required: false,
        defaultValue: "true",
        description: "true para entero, false para decimal",
      },
    ],
    outputs: [
      { key: "result", type: NodeDataType.NUMBER, description: "Número aleatorio generado" },
    ],
  },
  {
    name: "Get Date/Time",
    fnKey: "datetime.get",
    category: "utility",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "timezone",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description:
          "Zona horaria (ej: America/Argentina/Buenos_Aires). Vacío = zona local del servidor",
      },
    ],
    outputs: [
      { key: "year", type: NodeDataType.NUMBER, description: "Año (ej: 2026)" },
      { key: "month", type: NodeDataType.NUMBER, description: "Mes (1-12)" },
      { key: "day", type: NodeDataType.NUMBER, description: "Día del mes (1-31)" },
      { key: "hour", type: NodeDataType.NUMBER, description: "Hora (0-23)" },
      { key: "minute", type: NodeDataType.NUMBER, description: "Minuto (0-59)" },
      { key: "second", type: NodeDataType.NUMBER, description: "Segundo (0-59)" },
      { key: "iso", type: NodeDataType.STRING, description: "Fecha/hora en formato ISO 8601" },
      { key: "timestamp", type: NodeDataType.NUMBER, description: "Timestamp en milisegundos" },
    ],
  },
  {
    name: "Math Operation",
    fnKey: "math.operation",
    category: "math",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "a",
        type: NodeDataType.NUMBER,
        input: "number",
        required: true,
        defaultValue: 0,
        description: "Primer valor",
      },
      {
        key: "b",
        type: NodeDataType.NUMBER,
        input: "number",
        required: true,
        defaultValue: 0,
        description: "Segundo valor",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["suma", "resta", "multiplicacion", "division", "potencia", "raiz", "modulo"],
        required: false,
        defaultValue: "suma",
        description: "Operación a realizar (raiz = raíz a-ésima de b)",
      },
    ],
    outputs: [
      { key: "result", type: NodeDataType.NUMBER, description: "Resultado de la operación" },
    ],
  },
  {
    name: "HTTP Request",
    fnKey: "http.request",
    category: "actions",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "url",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Request URL",
      },
      {
        key: "method",
        type: NodeDataType.STRING,
        input: "select",
        options: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        required: false,
        defaultValue: "GET",
        description: "HTTP method (GET, POST, PUT, DELETE)",
      },
      {
        key: "headers",
        type: NodeDataType.OBJECT,
        input: "none",
        required: false,
        description: "Request headers as JSON object",
      },
      {
        key: "body",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Request body",
      },
      {
        key: "authType",
        type: NodeDataType.STRING,
        input: "select",
        options: ["none", "bearer", "basic", "api_key"],
        required: false,
        defaultValue: "none",
        description: "Tipo de autenticación automática",
      },
      {
        key: "authToken",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Token para Bearer auth (sk-..., token-...)",
      },
      {
        key: "authUsername",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Username para Basic auth",
      },
      {
        key: "authPassword",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Password para Basic auth",
      },
      {
        key: "authApiKey",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "API Key para api_key auth",
      },
      {
        key: "authKeyName",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "X-API-Key",
        description: "Nombre del header/query param para API key",
      },
      {
        key: "authKeyLocation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["header", "query"],
        required: false,
        defaultValue: "header",
        description: "Ubicación de la API key (header o query param)",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "HTTP status code" },
      { key: "data", type: NodeDataType.ANY, description: "Response body" },
      { key: "headers", type: NodeDataType.OBJECT, description: "Response headers" },
    ],
  },
  {
    name: "Web Search",
    fnKey: "web.search",
    category: "actions",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "query",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Consulta de búsqueda",
      },
      {
        key: "maxResults",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 5,
        description: "Máximo de resultados (1-10)",
      },
    ],
    outputs: [
      {
        key: "summary",
        type: NodeDataType.STRING,
        description: "Resumen formateado de los resultados",
      },
      {
        key: "results",
        type: NodeDataType.ANY_ARRAY,
        description: "Array de resultados (title, snippet, url)",
      },
      {
        key: "count",
        type: NodeDataType.NUMBER,
        description: "Cantidad de resultados encontrados",
      },
    ],
  },
  {
    name: "Number Formatter",
    fnKey: "number.format",
    category: "utility",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "value",
        type: NodeDataType.NUMBER,
        input: "number",
        required: true,
        description: "Número a formatear",
      },
      {
        key: "format",
        type: NodeDataType.STRING,
        input: "select",
        options: ["decimal", "currency", "percentage", "compact", "scientific"],
        required: false,
        defaultValue: "decimal",
        description: "Tipo de formato",
      },
      {
        key: "decimals",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 2,
        description: "Cantidad de decimales",
      },
      {
        key: "currency",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "USD",
        description: "Código de moneda (USD, EUR, ARS, etc.)",
      },
      {
        key: "locale",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "en-US",
        description: "Locale (en-US, es-AR, etc.)",
      },
    ],
    outputs: [
      { key: "formatted", type: NodeDataType.STRING, description: "Número formateado" },
      { key: "value", type: NodeDataType.NUMBER, description: "Valor original" },
    ],
  },
  {
    name: "Date Formatter",
    fnKey: "date.format",
    category: "utility",
    version: 1,
    publicTool: true,
    inputs: [
      {
        key: "date",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Fecha ISO (vacío = ahora)",
      },
      {
        key: "format",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "DD/MM/YYYY HH:mm",
        description: "Formato: YYYY, MM, DD, HH, mm, ss",
      },
      {
        key: "timezone",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Zona horaria (ej: America/Argentina/Buenos_Aires)",
      },
    ],
    outputs: [
      { key: "formatted", type: NodeDataType.STRING, description: "Fecha formateada" },
      { key: "date", type: NodeDataType.STRING, description: "Fecha ISO completa" },
      {
        key: "relative",
        type: NodeDataType.STRING,
        description: "Tiempo relativo (hace X horas, etc.)",
      },
      { key: "timestamp", type: NodeDataType.NUMBER, description: "Timestamp en ms" },
    ],
  },
  {
    name: "Counter",
    fnKey: "counter",
    category: "utility",
    version: 1,
    inputs: [
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["increment", "decrement", "reset", "set"],
        required: false,
        defaultValue: "increment",
        description: "Operación a realizar",
      },
      {
        key: "step",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Valor de incremento/decremento (o valor para set)",
      },
      {
        key: "start",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0,
        description: "Valor inicial (para reset)",
      },
    ],
    outputs: [
      { key: "value", type: NodeDataType.NUMBER, description: "Valor actual del contador" },
      { key: "previousValue", type: NodeDataType.NUMBER, description: "Valor anterior" },
      { key: "operation", type: NodeDataType.STRING, description: "Operación realizada" },
    ],
  },
  {
    name: "Accumulator",
    fnKey: "accumulator",
    category: "utility",
    version: 1,
    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: true,
        description: "Valor a acumular",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["append", "prepend", "flatten", "count", "sum", "reset"],
        required: false,
        defaultValue: "append",
        description: "Operación de acumulación",
      },
      {
        key: "separator",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Separador para join",
      },
    ],
    outputs: [
      { key: "items", type: NodeDataType.ANY_ARRAY, description: "Array acumulado" },
      {
        key: "result",
        type: NodeDataType.ANY,
        description: "Resultado (array o número según operación)",
      },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de items" },
    ],
  },
  {
    name: "Webhook Wait",
    fnKey: "webhook.wait",
    category: "utility",
    version: 1,
    inputs: [
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Timeout en segundos (default 300 = 5 min)",
      },
    ],
    outputs: [
      { key: "data", type: NodeDataType.ANY, description: "Datos recibidos del webhook" },
      { key: "receivedAt", type: NodeDataType.STRING, description: "Fecha/hora de recepción" },
    ],
  },
  {
    name: "Retry",
    fnKey: "retry",
    category: "utility",
    version: 1,
    inputs: [
      {
        key: "nodeDefinitionId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del nodo a reintentar",
      },
      {
        key: "maxRetries",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 3,
        description: "Cantidad máxima de reintentos",
      },
      {
        key: "initialDelay",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Delay inicial en segundos",
      },
      {
        key: "maxDelay",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 30,
        description: "Delay máximo en segundos",
      },
      {
        key: "backoffMultiplier",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 2,
        description: "Multiplicador de backoff",
      },
    ],
    outputs: [
      { key: "attempts", type: NodeDataType.NUMBER, description: "Intentos realizados" },
      { key: "success", type: NodeDataType.BOOLEAN, description: "Si tuvo éxito" },
    ],
  },
  {
    name: "AI Chat",
    fnKey: "ai.chat",
    category: "ai",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "model",
        type: NodeDataType.STRING,
        input: "select",
        options: [
          "gpt-5-nano",
          "gpt-5.4-nano",
          "gpt-5.5",
          "claude-sonnet-4-6",
          "claude-opus-4-8",
          "gemini-3.1-flash-lite",
          "gemini-3.1-flash",
          "openai/gpt-5.3-chat",
          "reka/reka-edge",
        ],
        required: false,
        defaultValue: "gpt-5-nano",
        description: "Modelo a usar (requiere Puter conectado)",
      },
      {
        key: "system",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        description: "Prompt de sistema opcional",
      },
      {
        key: "messages",
        type: NodeDataType.JSON,
        input: "textarea",
        required: true,
        description: 'Mensajes JSON, ej: [{"role":"user","content":"hola"}]',
      },
      {
        key: "temperature",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0.7,
        description: "Temperatura (0-2)",
      },
      {
        key: "maxTokens",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 2048,
        description: "Máximo de tokens en la respuesta",
      },
    ],
    outputs: [
      { key: "response", type: NodeDataType.STRING, description: "Respuesta generada" },
      { key: "model", type: NodeDataType.STRING, description: "Modelo usado" },
    ],
  },
  {
    name: "AI Assistant",
    fnKey: "ai.assistant",
    category: "ai",
    version: 1,

    inputs: [
      {
        key: "assistantId",
        type: NodeDataType.STRING,
        input: "select",
        options: [],
        required: true,
        description: "Asistente a usar (los de la sección Asistentes)",
      },
      {
        key: "prompt",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Prompt a enviar al asistente",
      },
    ],
    outputs: [
      { key: "response", type: NodeDataType.STRING, description: "Respuesta del asistente" },
      { key: "assistantName", type: NodeDataType.STRING, description: "Nombre del asistente" },
      { key: "model", type: NodeDataType.STRING, description: "Modelo usado" },
    ],
  },
  {
    name: "Gmail Send Email",
    fnKey: "gmail.send",
    category: "email",
    version: 1,
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Gmail",
      },
      {
        key: "to",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Recipient email",
      },
      {
        key: "subject",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Email subject",
      },
      {
        key: "body",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Email body (plain text)",
      },
    ],
    outputs: [
      { key: "messageId", type: NodeDataType.STRING, description: "Message ID from Gmail" },
    ],
  },
  {
    name: "Outlook Send Email",
    fnKey: "outlook.send",
    category: "email",
    version: 1,

    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Outlook",
      },
      {
        key: "to",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Recipient email",
      },
      {
        key: "subject",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Email subject",
      },
      {
        key: "body",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Email body (plain text)",
      },
    ],
    outputs: [
      { key: "messageId", type: NodeDataType.STRING, description: "Message ID from Outlook" },
    ],
  },
  {
    name: "Stringify Object",
    fnKey: "json.stringify",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: true,
        description: "Objeto o dato a convertir",
      },
    ],
    outputs: [
      { key: "text", type: NodeDataType.STRING, description: "Objeto serializado como texto" },
    ],
  },
  {
    name: "Parse Object",
    fnKey: "json.parse",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Texto JSON a parsear",
      },
    ],
    outputs: [{ key: "value", type: NodeDataType.ANY, description: "Valor parseado" }],
  },
  {
    name: "Get Value From Object",
    fnKey: "json.get",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "object",
        type: NodeDataType.OBJECT,
        input: "none",
        required: true,
        description: "Objeto de origen",
      },
      {
        key: "key",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Clave a leer",
      },
    ],
    outputs: [{ key: "value", type: NodeDataType.ANY, description: "Valor de la clave" }],
  },
  {
    name: "Get Array Element",
    fnKey: "array.get",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "array",
        type: NodeDataType.ANY_ARRAY,
        input: "none",
        required: true,
        description: "Array o string (se trata como array de caracteres)",
      },
      {
        key: "index",
        type: NodeDataType.NUMBER,
        input: "number",
        required: true,
        defaultValue: 0,
        description: "Índice del elemento a obtener",
      },
    ],
    outputs: [
      { key: "value", type: NodeDataType.ANY, description: "Elemento en la posición index" },
    ],
  },
  {
    name: "Array Aggregate",
    fnKey: "array.aggregate",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "array",
        type: NodeDataType.NUMBER_ARRAY,
        input: "none",
        required: true,
        description: "Array de números a procesar",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["sum", "avg", "max", "min"],
        required: false,
        defaultValue: "sum",
        description: "Operación a aplicar sobre el array",
      },
    ],
    outputs: [
      { key: "result", type: NodeDataType.NUMBER, description: "Resultado de la operación" },
    ],
  },
  {
    name: "Array Length",
    fnKey: "array.length",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY_ARRAY,
        input: "none",
        required: true,
        description: "Array o string a medir",
      },
    ],
    outputs: [{ key: "length", type: NodeDataType.NUMBER, description: "Cantidad de elementos" }],
  },
  {
    name: "Array Operations",
    fnKey: "array.operations",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "array",
        type: NodeDataType.ANY_ARRAY,
        input: "none",
        required: true,
        description: "Array o string a operar",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["push", "join", "filter", "map", "concat", "slice"],
        required: false,
        defaultValue: "push",
        description: "Operación a aplicar",
      },
      {
        key: "value",
        type: NodeDataType.ANY_ARRAY,
        input: "none",
        required: false,
        description: "Elemento a agregar (push) u otro array (concat)",
      },
      {
        key: "separator",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "",
        description: "Separador para join",
      },
      {
        key: "start",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0,
        description: "Índice inicial para slice",
      },
      {
        key: "end",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        description: "Índice final para slice (opcional)",
      },
      {
        key: "expression",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        description: "Expresión JS para filter/map. Variables: item, index, array. Ej: item > 5",
      },
    ],
    outputs: [{ key: "result", type: NodeDataType.ANY, description: "Resultado (array o string)" }],
  },
  {
    name: "Text Operations",
    fnKey: "text.operations",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Texto a procesar",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["split", "replace", "slice", "upper", "lower", "trim"],
        required: false,
        defaultValue: "trim",
        description: "Operación a aplicar",
      },
      {
        key: "separator",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: ",",
        description: "Separador para split",
      },
      {
        key: "search",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Texto a buscar para replace",
      },
      {
        key: "replacement",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "",
        description: "Texto de reemplazo (todas las ocurrencias)",
      },
      {
        key: "start",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0,
        description: "Índice inicial para slice",
      },
      {
        key: "end",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        description: "Índice final para slice (opcional)",
      },
    ],
    outputs: [{ key: "result", type: NodeDataType.ANY, description: "Resultado (string o array)" }],
  },
  {
    name: "If/Else",
    fnKey: "if.else",
    category: "logic",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "value1",
        type: NodeDataType.ANY,
        input: "none",
        required: true,
        description: "Primer valor a comparar",
      },
      {
        key: "value2",
        type: NodeDataType.ANY,
        input: "none",
        required: true,
        description: "Segundo valor a comparar",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["=", ">", "<", ">=", "<="],
        required: false,
        defaultValue: "=",
        description: "Operación de comparación",
      },
    ],
    outputs: [
      {
        key: "true",
        type: NodeDataType.ANY,
        description: "Salida cuando la condición es verdadera",
      },
      { key: "false", type: NodeDataType.ANY, description: "Salida cuando la condición es falsa" },
    ],
  },
  {
    name: "OR Gate",
    fnKey: "or.gate",
    category: "logic",
    version: 1,
    scope: "workflow",
    activationMode: "any",
    inputs: [
      {
        key: "input1",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Primera entrada (se activa con cualquiera)",
      },
      {
        key: "input2",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Segunda entrada",
      },
      {
        key: "input3",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Tercera entrada",
      },
      {
        key: "input4",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Cuarta entrada",
      },
    ],
    outputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        description: "Dato de la primera entrada que recibe datos",
      },
    ],
  },
  {
    name: "Switch",
    fnKey: "switch",
    category: "logic",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: true,
        description: "Valor a evaluar",
      },
      {
        key: "cases",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        defaultValue: "",
        description:
          'Casos separados por coma. Usá comillas (simples o dobles) para incluir comas u otras comillas, ej: activo, pendiente, "en espera"',
      },
    ],
    outputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        description: "Dato de la primera entrada que recibe datos",
      },
    ],
  },
  {
    name: "Return/End",
    fnKey: "return.end",
    category: "logic",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Valor a devolver como resultado del workflow",
      },
    ],
    outputs: [],
  },
  {
    name: "Try/Catch",
    fnKey: "try.catch",
    category: "logic",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Valor a pasar al bloque try",
      },
    ],
    outputs: [
      {
        key: "try",
        type: NodeDataType.ANY,
        description: "Se activa cuando comienza el bloque try",
      },
      {
        key: "catch",
        type: NodeDataType.ANY,
        description: "Se activa si algún nodo del bloque try falla, con el error",
      },
    ],
  },
  {
    name: "File Upload",
    fnKey: "file.upload",
    category: "files",
    version: 1,

    inputs: [
      {
        key: "file",
        type: NodeDataType.FILE,
        input: "file",
        required: true,
        description: "Archivo a subir (se elige al ejecutar)",
      },
    ],
    outputs: [
      { key: "url", type: NodeDataType.STRING, description: "URL del archivo subido" },
      { key: "key", type: NodeDataType.STRING, description: "Clave S3 del archivo" },
      { key: "name", type: NodeDataType.STRING, description: "Nombre original del archivo" },
      { key: "size", type: NodeDataType.NUMBER, description: "Tamaño en bytes" },
      { key: "type", type: NodeDataType.STRING, description: "Tipo MIME" },
    ],
  },
  {
    name: "File Parser",
    fnKey: "file.parser",
    category: "files",
    version: 1,

    inputs: [
      {
        key: "url",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "URL del archivo (salida de File Upload)",
      },
    ],
    outputs: [
      { key: "text", type: NodeDataType.STRING, description: "Contenido extraído" },
      { key: "format", type: NodeDataType.STRING, description: "Formato detectado" },
      { key: "rows", type: NodeDataType.ANY_ARRAY, description: "Filas parseadas (csv/xlsx)" },
    ],
  },
  {
    name: "Template",
    fnKey: "template.render",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "template",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Texto con placeholders {{clave}} o {{a.b}}",
      },
      {
        key: "values",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: false,
        defaultValue: "{}",
        description: "Objeto con los valores (JSON)",
      },
    ],
    outputs: [{ key: "text", type: NodeDataType.STRING, description: "Template renderizado" }],
  },
  {
    name: "Object Operations",
    fnKey: "object.operations",
    category: "data",
    version: 1,
    publicTool: true,

    inputs: [
      {
        key: "mode",
        type: NodeDataType.STRING,
        input: "select",
        options: ["merge", "set"],
        required: false,
        defaultValue: "merge",
        description: "merge: combinar objetos · set: asignar una clave",
      },
      {
        key: "object1",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: false,
        description: "Primer objeto para merge (JSON)",
      },
      {
        key: "object2",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: false,
        description: "Segundo objeto para merge (JSON, gana en conflicto)",
      },
      {
        key: "object",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: false,
        description: "Objeto base para set (JSON)",
      },
      {
        key: "key",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Clave a asignar (set)",
      },
      {
        key: "value",
        type: NodeDataType.ANY,
        input: "none",
        required: false,
        description: "Valor a asignar (set)",
      },
    ],
    outputs: [{ key: "result", type: NodeDataType.OBJECT, description: "Objeto resultante" }],
  },
  {
    name: "Slack Send Message",
    fnKey: "slack.send",
    category: "notifications",
    version: 1,

    inputs: [
      {
        key: "webhookUrl",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "URL del Incoming Webhook de Slack",
      },
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Mensaje a enviar",
      },
      {
        key: "channel",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Canal opcional (#general)",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "data", type: NodeDataType.ANY, description: "Respuesta" },
    ],
  },
  {
    name: "Discord Send Message",
    fnKey: "discord.send",
    category: "notifications",
    version: 1,

    inputs: [
      {
        key: "webhookUrl",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "URL del Webhook de Discord",
      },
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Mensaje a enviar",
      },
      {
        key: "username",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Nombre de usuario opcional",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "data", type: NodeDataType.ANY, description: "Respuesta" },
    ],
  },
  {
    name: "Telegram Send Message",
    fnKey: "telegram.send",
    category: "notifications",
    version: 1,

    inputs: [
      {
        key: "botToken",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Token del bot (de @BotFather)",
      },
      {
        key: "chatId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del chat (usuario o grupo)",
      },
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Mensaje a enviar",
      },
      {
        key: "parseMode",
        type: NodeDataType.STRING,
        input: "select",
        options: ["", "HTML", "Markdown"],
        required: false,
        defaultValue: "",
        description: "Formato del mensaje",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "data", type: NodeDataType.ANY, description: "Respuesta" },
    ],
  },
  {
    name: "Airtable List Records",
    fnKey: "airtable.list",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "token",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Personal Access Token de Airtable",
      },
      {
        key: "baseId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la base",
      },
      {
        key: "tableName",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre de la tabla",
      },
      {
        key: "limit",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Máximo de registros",
      },
      {
        key: "view",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Vista opcional",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "records", type: NodeDataType.ANY_ARRAY, description: "Registros crudos" },
      { key: "rows", type: NodeDataType.ANY_ARRAY, description: "Filas (id + campos)" },
    ],
  },
  {
    name: "Airtable Append Record",
    fnKey: "airtable.append",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "token",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Personal Access Token de Airtable",
      },
      {
        key: "baseId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la base",
      },
      {
        key: "tableName",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre de la tabla",
      },
      {
        key: "fields",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: true,
        description: "Campos del registro (JSON)",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "data", type: NodeDataType.ANY, description: "Respuesta" },
    ],
  },
  {
    name: "Notion Create Page",
    fnKey: "notion.createPage",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "token",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Integration Token de Notion",
      },
      {
        key: "databaseId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la base de datos",
      },
      {
        key: "properties",
        type: NodeDataType.OBJECT,
        input: "textarea",
        required: true,
        description: "Propiedades de la página (JSON, según el schema de la base)",
      },
      {
        key: "children",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Bloques hijos opcionales (JSON array)",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "id", type: NodeDataType.STRING, description: "ID de la página" },
      { key: "url", type: NodeDataType.STRING, description: "URL de la página" },
      { key: "page", type: NodeDataType.OBJECT, description: "Página completa" },
    ],
  },
  {
    name: "Notion Read Database",
    fnKey: "notion.readDatabase",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "token",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Integration Token de Notion",
      },
      {
        key: "databaseId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la base de datos",
      },
      {
        key: "pageSize",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Máximo de páginas (1-100)",
      },
    ],
    outputs: [
      { key: "pages", type: NodeDataType.ANY_ARRAY, description: "Páginas con propiedades" },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de páginas" },
      { key: "hasMore", type: NodeDataType.BOOLEAN, description: "Si hay más páginas" },
      { key: "nextCursor", type: NodeDataType.STRING, description: "Cursor para paginación" },
    ],
  },
  {
    name: "Notion Query Database",
    fnKey: "notion.queryDatabase",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "token",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Integration Token de Notion",
      },
      {
        key: "databaseId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la base de datos",
      },
      {
        key: "filterProperty",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Propiedad para filtrar",
      },
      {
        key: "filterValue",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Valor del filtro",
      },
      {
        key: "sortProperty",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Propiedad para ordenar",
      },
      {
        key: "sortDirection",
        type: NodeDataType.STRING,
        input: "select",
        options: ["ascending", "descending"],
        required: false,
        defaultValue: "descending",
        description: "Dirección del orden",
      },
      {
        key: "pageSize",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Máximo de páginas",
      },
    ],
    outputs: [
      { key: "pages", type: NodeDataType.ANY_ARRAY, description: "Páginas filtradas" },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de resultados" },
    ],
  },
  {
    name: "Notion Update Page",
    fnKey: "notion.updatePage",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "token",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Integration Token de Notion",
      },
      {
        key: "pageId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID de la página a actualizar",
      },
      {
        key: "properties",
        type: NodeDataType.JSON,
        input: "textarea",
        required: true,
        description: "Propiedades a actualizar (JSON)",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID de la página" },
      { key: "url", type: NodeDataType.STRING, description: "URL de la página" },
      { key: "lastEdited", type: NodeDataType.STRING, description: "Última edición" },
    ],
  },
  {
    name: "Google Calendar Create Event",
    fnKey: "google.calendar.createEvent",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "accessToken",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Token de acceso de Google",
      },
      {
        key: "calendarId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "primary",
        description: "ID del calendario",
      },
      {
        key: "summary",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Título del evento",
      },
      {
        key: "description",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        description: "Descripción del evento",
      },
      {
        key: "start",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Fecha/hora inicio (ISO 8601)",
      },
      {
        key: "end",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Fecha/hora fin (ISO 8601)",
      },
      {
        key: "location",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Ubicación",
      },
      {
        key: "timezone",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "UTC",
        description: "Zona horaria",
      },
    ],
    outputs: [
      { key: "eventId", type: NodeDataType.STRING, description: "ID del evento" },
      { key: "htmlLink", type: NodeDataType.STRING, description: "URL del evento" },
      { key: "status", type: NodeDataType.STRING, description: "Estado del evento" },
    ],
  },
  {
    name: "Google Calendar List Events",
    fnKey: "google.calendar.listEvents",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "accessToken",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Token de acceso de Google",
      },
      {
        key: "calendarId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "primary",
        description: "ID del calendario",
      },
      {
        key: "timeMin",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Fecha/hora mínima (ISO 8601)",
      },
      {
        key: "timeMax",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Fecha/hora máxima (ISO 8601)",
      },
      {
        key: "maxResults",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 10,
        description: "Máximo de eventos",
      },
      {
        key: "query",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Buscar en títulos/descripciones",
      },
      {
        key: "timezone",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "UTC",
        description: "Zona horaria",
      },
    ],
    outputs: [
      { key: "events", type: NodeDataType.ANY_ARRAY, description: "Lista de eventos" },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de eventos" },
    ],
  },
  {
    name: "Google Sheets",
    fnKey: "google.sheets",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Google",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["append", "read", "list", "update"],
        required: false,
        defaultValue: "append",
        description:
          "append: agregar filas · read: leer rango · list: listar hojas · update: escribir rango",
      },
      {
        key: "spreadsheetId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del spreadsheet (de la URL)",
      },
      {
        key: "sheetName",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "Sheet1",
        description: "Nombre de la hoja",
      },
      {
        key: "values",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: 'Filas a agregar (JSON array de arrays), ej: [["a",1],["b",2]]',
      },
      {
        key: "range",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "A1",
        description: "Rango a leer (read)",
      },
    ],
    outputs: [
      { key: "result", type: NodeDataType.ANY, description: "Respuesta" },
      { key: "values", type: NodeDataType.ANY_ARRAY, description: "Valores leídos (read)" },
    ],
  },
  {
    name: "Google Docs",
    fnKey: "google.docs",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Google",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["create", "list", "read", "update"],
        required: false,
        defaultValue: "create",
        description: "create: crear · list: listar · read: leer · update: reemplazar texto",
      },
      {
        key: "title",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Título del documento (create)",
      },
      {
        key: "content",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        description: "Contenido del documento (create, texto plano)",
      },
      {
        key: "documentId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID del documento (read/update)",
      },
      {
        key: "find",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Texto a reemplazar (update)",
      },
      {
        key: "replacement",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "",
        description: "Texto de reemplazo (update, todas las ocurrencias)",
      },
    ],
    outputs: [
      { key: "documentId", type: NodeDataType.STRING, description: "ID del documento" },
      { key: "url", type: NodeDataType.STRING, description: "URL del documento" },
      { key: "files", type: NodeDataType.ANY_ARRAY, description: "Lista de documentos (list)" },
      { key: "text", type: NodeDataType.STRING, description: "Texto extraído (read)" },
      {
        key: "occurrencesReplaced",
        type: NodeDataType.NUMBER,
        description: "Ocurrencias reemplazadas (update)",
      },
    ],
  },
  {
    name: "Google Slides",
    fnKey: "google.slides",
    category: "integrations",
    version: 1,

    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Google",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["create", "list", "read", "update"],
        required: false,
        defaultValue: "create",
        description: "create: crear · list: listar · read: leer · update: agregar diapositiva",
      },
      {
        key: "title",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Título (create) o título de la nueva diapositiva (update)",
      },
      {
        key: "presentationId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID de la presentación (read/update)",
      },
    ],
    outputs: [
      { key: "presentationId", type: NodeDataType.STRING, description: "ID de la presentación" },
      { key: "url", type: NodeDataType.STRING, description: "URL de la presentación" },
      { key: "files", type: NodeDataType.ANY_ARRAY, description: "Lista de presentaciones (list)" },
      { key: "slides", type: NodeDataType.ANY_ARRAY, description: "Diapositivas (read)" },
      {
        key: "slideCount",
        type: NodeDataType.NUMBER,
        description: "Cantidad de diapositivas (read)",
      },
      {
        key: "slideId",
        type: NodeDataType.STRING,
        description: "ID de la nueva diapositiva (update)",
      },
    ],
  },
  {
    name: "Stripe Charge",
    fnKey: "stripe.charge",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "secretKey",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Stripe Secret Key (sk_...)",
      },
      {
        key: "amount",
        type: NodeDataType.NUMBER,
        input: "number",
        required: true,
        description: "Monto en la moneda base (ej: 29.99)",
      },
      {
        key: "currency",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        defaultValue: "usd",
        description: "Moneda (usd, eur, ars, etc.)",
      },
      {
        key: "description",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Descripción del cargo",
      },
      {
        key: "customerId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID del cliente (cus_...)",
      },
      {
        key: "metadata",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Metadata adicional (JSON)",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID del payment intent" },
      { key: "status", type: NodeDataType.STRING, description: "Estado del pago" },
      { key: "amount", type: NodeDataType.NUMBER, description: "Monto cobrado" },
      { key: "currency", type: NodeDataType.STRING, description: "Moneda" },
      {
        key: "client_secret",
        type: NodeDataType.STRING,
        description: "Client secret para frontend",
      },
    ],
  },
  {
    name: "Stripe Customer",
    fnKey: "stripe.customer",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "secretKey",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Stripe Secret Key (sk_...)",
      },
      {
        key: "email",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Email del cliente",
      },
      {
        key: "name",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Nombre del cliente",
      },
      {
        key: "phone",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Teléfono",
      },
      {
        key: "description",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Descripción",
      },
      {
        key: "metadata",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Metadata (JSON)",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID del cliente (cus_...)" },
      { key: "email", type: NodeDataType.STRING, description: "Email" },
      { key: "name", type: NodeDataType.STRING, description: "Nombre" },
      { key: "created", type: NodeDataType.NUMBER, description: "Fecha de creación" },
    ],
  },
  {
    name: "Stripe Subscription",
    fnKey: "stripe.subscription",
    category: "integrations",
    version: 1,
    inputs: [
      {
        key: "secretKey",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Stripe Secret Key (sk_...)",
      },
      {
        key: "customerId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del cliente (cus_...)",
      },
      {
        key: "priceId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del precio (price_...)",
      },
      {
        key: "trialDays",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0,
        description: "Días de prueba",
      },
      {
        key: "metadata",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Metadata (JSON)",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID de la suscripción" },
      { key: "status", type: NodeDataType.STRING, description: "Estado" },
      {
        key: "current_period_end",
        type: NodeDataType.NUMBER,
        description: "Fin del período actual",
      },
    ],
  },
  {
    name: "OpenAI Chat",
    fnKey: "openai.chat",
    category: "ai",
    version: 1,
    inputs: [
      {
        key: "apiKey",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "API Key de OpenAI (sk-...)",
      },
      {
        key: "model",
        type: NodeDataType.STRING,
        input: "select",
        options: [
          "gpt-4o",
          "gpt-4o-mini",
          "gpt-4-turbo",
          "gpt-4",
          "gpt-3.5-turbo",
          "o1-preview",
          "o1-mini",
        ],
        required: false,
        defaultValue: "gpt-4o-mini",
        description: "Modelo a usar",
      },
      {
        key: "system",
        type: NodeDataType.STRING,
        input: "textarea",
        required: false,
        description: "System prompt",
      },
      {
        key: "messages",
        type: NodeDataType.JSON,
        input: "textarea",
        required: true,
        description: 'Mensajes JSON, ej: [{"role":"user","content":"hola"}]',
      },
      {
        key: "temperature",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 0.7,
        description: "Temperatura (0-2)",
      },
      {
        key: "maxTokens",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 2048,
        description: "Máximo de tokens",
      },
    ],
    outputs: [
      { key: "response", type: NodeDataType.STRING, description: "Respuesta generada" },
      { key: "model", type: NodeDataType.STRING, description: "Modelo usado" },
      { key: "finishReason", type: NodeDataType.STRING, description: "Razón de finalización" },
      { key: "totalTokens", type: NodeDataType.NUMBER, description: "Total de tokens usados" },
    ],
  },
  {
    name: "Supabase Query",
    fnKey: "supabase.query",
    category: "database",
    version: 1,
    inputs: [
      {
        key: "supabaseUrl",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "URL de tu proyecto Supabase",
      },
      {
        key: "apiKey",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Supabase anon/service key",
      },
      {
        key: "table",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre de la tabla",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["select", "insert", "update", "delete", "upsert"],
        required: false,
        defaultValue: "select",
        description: "Operación a realizar",
      },
      {
        key: "filter",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Filtro (select: column=eq.value, delete/update: column=eq.value)",
      },
      {
        key: "data",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Datos para insert/update/upsert (JSON)",
      },
      {
        key: "limit",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Límite de resultados",
      },
    ],
    outputs: [
      { key: "data", type: NodeDataType.ANY, description: "Resultado de la operación" },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de registros" },
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
    ],
  },
  {
    name: "Firebase Query",
    fnKey: "firebase.query",
    category: "database",
    version: 1,
    inputs: [
      {
        key: "projectId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del proyecto Firebase",
      },
      {
        key: "serviceAccountKey",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Service Account Key (JSON completo)",
      },
      {
        key: "collection",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre de la colección",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["get", "list", "create", "update", "delete"],
        required: false,
        defaultValue: "get",
        description: "Operación",
      },
      {
        key: "documentId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID del documento (get/update/delete)",
      },
      {
        key: "data",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Datos para create/update (JSON)",
      },
      {
        key: "filterField",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Campo para filtrar (list)",
      },
      {
        key: "filterValue",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Valor del filtro (list)",
      },
      {
        key: "limit",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Límite (list)",
      },
    ],
    outputs: [
      { key: "data", type: NodeDataType.ANY, description: "Resultado" },
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
    ],
  },
  {
    name: "Mongo Query",
    fnKey: "mongo.query",
    category: "database",
    version: 1,

    inputs: [
      {
        key: "collection",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre de la colección",
      },
      {
        key: "operation",
        type: NodeDataType.STRING,
        input: "select",
        options: ["find", "insertOne", "updateOne", "deleteOne", "count"],
        required: false,
        defaultValue: "find",
        description: "Operación",
      },
      {
        key: "query",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        defaultValue: "{}",
        description: "Filtro (JSON)",
      },
      {
        key: "data",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Documento o update (JSON) para insertOne/updateOne",
      },
      {
        key: "limit",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 100,
        description: "Máximo de documentos (find)",
      },
    ],
    outputs: [{ key: "result", type: NodeDataType.ANY, description: "Resultado de la operación" }],
  },
  {
    name: "Postgres Query",
    fnKey: "postgres.query",
    category: "database",
    version: 1,

    inputs: [
      {
        key: "connectionString",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "postgres://usuario:pass@host:puerto/db",
      },
      {
        key: "query",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Consulta SQL",
      },
      {
        key: "params",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Parámetros (JSON array) para $1, $2…",
      },
    ],
    outputs: [
      { key: "rows", type: NodeDataType.ANY_ARRAY, description: "Filas resultantes" },
      { key: "rowCount", type: NodeDataType.NUMBER, description: "Cantidad de filas" },
      { key: "fields", type: NodeDataType.ANY_ARRAY, description: "Campos" },
    ],
  },
  {
    name: "MySQL Query",
    fnKey: "mysql.query",
    category: "database",
    version: 1,

    inputs: [
      {
        key: "connectionString",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "mysql://usuario:pass@host:puerto/db",
      },
      {
        key: "query",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Consulta SQL",
      },
      {
        key: "params",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Parámetros (JSON array) para ?",
      },
    ],
    outputs: [{ key: "result", type: NodeDataType.ANY, description: "Resultado" }],
  },
  {
    name: "Webhook Trigger",
    fnKey: "webhook.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [],
    outputs: [
      {
        key: "data",
        type: NodeDataType.ANY,
        description: "Payload del webhook (POST /api/webhooks/:id)",
      },
    ],
  },
  {
    name: "Schedule Trigger",
    fnKey: "schedule.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "intervalSeconds",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 60,
        description: "Cada cuántos segundos se ejecuta",
      },
    ],
    outputs: [
      { key: "timestamp", type: NodeDataType.STRING, description: "Marca de tiempo ISO" },
      { key: "now", type: NodeDataType.NUMBER, description: "Timestamp en ms" },
    ],
  },
  {
    name: "Slack Trigger",
    fnKey: "slack.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu workspace de Slack",
      },
      {
        key: "channelId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID del canal a escuchar (vacío = cualquiera)",
      },
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Segundos a esperar por un mensaje nuevo (default 300)",
      },
    ],
    outputs: [
      { key: "channel", type: NodeDataType.STRING, description: "Canal de donde vino el mensaje" },
      { key: "user", type: NodeDataType.STRING, description: "Usuario que envió el mensaje" },
      { key: "text", type: NodeDataType.STRING, description: "Contenido del mensaje" },
      { key: "team", type: NodeDataType.STRING, description: "Workspace de Slack" },
      { key: "timestamp", type: NodeDataType.STRING, description: "Timestamp del mensaje" },
      { key: "messageType", type: NodeDataType.STRING, description: "channel, dm, o group" },
    ],
  },
  {
    name: "Discord Trigger",
    fnKey: "discord.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu bot de Discord",
      },
      {
        key: "channelId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "ID del canal a escuchar (vacío = cualquiera)",
      },
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Segundos a esperar por un mensaje nuevo (default 300)",
      },
    ],
    outputs: [
      { key: "channelId", type: NodeDataType.STRING, description: "ID del canal" },
      { key: "author", type: NodeDataType.STRING, description: "Usuario que envió el mensaje" },
      { key: "content", type: NodeDataType.STRING, description: "Contenido del mensaje" },
      { key: "guildId", type: NodeDataType.STRING, description: "ID del servidor (null en DMs)" },
      { key: "timestamp", type: NodeDataType.STRING, description: "Timestamp del mensaje" },
      { key: "messageType", type: NodeDataType.STRING, description: "channel, dm, o group" },
    ],
  },
  {
    name: "Gmail Trigger",
    fnKey: "gmail.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Gmail",
      },
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Segundos a esperar por un email nuevo (default 300)",
      },
    ],
    outputs: [
      { key: "from", type: NodeDataType.STRING, description: "Email del remitente" },
      { key: "subject", type: NodeDataType.STRING, description: "Asunto del email" },
      { key: "body", type: NodeDataType.STRING, description: "Contenido del email" },
      { key: "date", type: NodeDataType.STRING, description: "Fecha de recepción" },
      { key: "attachments", type: NodeDataType.ANY_ARRAY, description: "Archivos adjuntos" },
    ],
  },
  {
    name: "Outlook Trigger",
    fnKey: "outlook.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de Outlook",
      },
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Segundos a esperar por un email nuevo (default 300)",
      },
    ],
    outputs: [
      { key: "from", type: NodeDataType.STRING, description: "Email del remitente" },
      { key: "subject", type: NodeDataType.STRING, description: "Asunto del email" },
      { key: "body", type: NodeDataType.STRING, description: "Contenido del email" },
      { key: "date", type: NodeDataType.STRING, description: "Fecha de recepción" },
      { key: "attachments", type: NodeDataType.ANY_ARRAY, description: "Archivos adjuntos" },
    ],
  },
  {
    name: "WhatsApp Send Message",
    fnKey: "whatsapp.send",
    category: "notifications",
    version: 1,
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: false,
        description:
          "Conectá tu cuenta de WhatsApp Business (OAuth) — si lo usás, no hace falta Access Token",
      },
      {
        key: "phoneNumberId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description:
          "Phone Number ID (de Meta Business) — dejalo vacío para auto-detectar con credentials",
      },
      {
        key: "accessToken",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Access Token de WhatsApp Business API (si no usás credentials)",
      },
      {
        key: "to",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Número de teléfono del destinatario (con código de país)",
      },
      {
        key: "text",
        type: NodeDataType.STRING,
        input: "textarea",
        required: true,
        description: "Mensaje a enviar",
      },
    ],
    outputs: [
      { key: "status", type: NodeDataType.NUMBER, description: "Código HTTP" },
      { key: "messageId", type: NodeDataType.STRING, description: "ID del mensaje enviado" },
      { key: "data", type: NodeDataType.ANY, description: "Respuesta completa" },
    ],
  },
  {
    name: "WhatsApp Trigger",
    fnKey: "whatsapp.trigger",
    category: "triggers",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "credentials",
        type: NodeDataType.CREDENTIALS,
        input: "credentials",
        required: true,
        description: "Conectá tu cuenta de WhatsApp Business",
      },
      {
        key: "phoneNumberId",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Phone Number ID de WhatsApp (vacío = cualquier número de tu cuenta)",
      },
      {
        key: "timeout",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 300,
        description: "Segundos a esperar por un mensaje nuevo (default 300)",
      },
    ],
    outputs: [
      { key: "from", type: NodeDataType.STRING, description: "Número del remitente" },
      { key: "name", type: NodeDataType.STRING, description: "Nombre del remitente" },
      { key: "text", type: NodeDataType.STRING, description: "Contenido del mensaje" },
      { key: "messageId", type: NodeDataType.STRING, description: "ID del mensaje" },
      { key: "timestamp", type: NodeDataType.STRING, description: "Timestamp del mensaje" },
    ],
  },
  {
    name: "Run Workflow",
    fnKey: "run.workflow",
    category: "flow",
    version: 1,
    scope: "all",
    inputs: [
      {
        key: "workflowId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del workflow hijo (doble click para abrirlo)",
      },
      {
        key: "inputCount",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Cantidad de inputs",
      },
      {
        key: "outputCount",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Cantidad de outputs",
      },
    ],
    outputs: [],
  },
  {
    name: "Get Inputs",
    fnKey: "get.inputs",
    category: "flow",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "count",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Cantidad de inputs que recibe del padre",
      },
    ],
    outputs: [],
  },
  {
    name: "Send Outputs",
    fnKey: "send.outputs",
    category: "flow",
    version: 1,
    scope: "workflow",
    inputs: [
      {
        key: "count",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 1,
        description: "Cantidad de outputs a enviar al padre",
      },
    ],
    outputs: [],
  },
  {
    name: "Create Workflow",
    fnKey: "create.workflow",
    category: "flow",
    version: 1,
    inputs: [
      {
        key: "name",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "Nombre del nuevo workflow",
      },
      {
        key: "nodes",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description:
          "Nodos del workflow (JSON array) — opcional, crea un workflow vacío si se omite",
      },
      {
        key: "edges",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Conexiones del workflow (JSON array) — opcional",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID del workflow creado" },
      { key: "url", type: NodeDataType.STRING, description: "URL para abrir el workflow" },
      { key: "name", type: NodeDataType.STRING, description: "Nombre del workflow creado" },
    ],
  },
  {
    name: "Edit Workflow",
    fnKey: "edit.workflow",
    category: "flow",
    version: 1,
    scope: "all",
    inputs: [
      {
        key: "workflowId",
        type: NodeDataType.STRING,
        input: "text",
        required: true,
        description: "ID del workflow a editar",
      },
      {
        key: "name",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Nuevo nombre del workflow (opcional)",
      },
      {
        key: "nodes",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Array completo de nodos — reemplaza los existentes (opcional)",
      },
      {
        key: "edges",
        type: NodeDataType.JSON,
        input: "textarea",
        required: false,
        description: "Array completo de conexiones — reemplaza las existentes (opcional)",
      },
    ],
    outputs: [
      { key: "id", type: NodeDataType.STRING, description: "ID del workflow editado" },
      { key: "url", type: NodeDataType.STRING, description: "URL para abrir el workflow" },
      { key: "name", type: NodeDataType.STRING, description: "Nombre del workflow" },
      { key: "nodeCount", type: NodeDataType.NUMBER, description: "Cantidad de nodos" },
      { key: "edgeCount", type: NodeDataType.NUMBER, description: "Cantidad de conexiones" },
    ],
  },
  {
    name: "List Workflows",
    fnKey: "list.workflows",
    category: "flow",
    version: 1,
    inputs: [
      {
        key: "search",
        type: NodeDataType.STRING,
        input: "text",
        required: false,
        description: "Busca workflows por nombre (opcional)",
      },
      {
        key: "limit",
        type: NodeDataType.NUMBER,
        input: "number",
        required: false,
        defaultValue: 50,
        description: "Máximo de resultados (1-200, default 50)",
      },
      {
        key: "includeChildren",
        type: NodeDataType.BOOLEAN,
        input: "none",
        required: false,
        defaultValue: false,
        description: "Si true, incluye workflows hijos (sub-workflows)",
      },
    ],
    outputs: [
      {
        key: "workflows",
        type: NodeDataType.ANY_ARRAY,
        description:
          "Lista de workflows (workflowId, name, parentWorkflowId, updatedAt, createdAt)",
      },
      { key: "count", type: NodeDataType.NUMBER, description: "Cantidad de resultados" },
    ],
  },
];

async function seed(): Promise<void> {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    for (const def of seedNodeDefinitions) {
      const updated = await NodeDefinition.findOneAndUpdate(
        { fnKey: def.fnKey },
        { $set: def },
        { upsert: true, returnDocument: "after", setDefaultsOnInsert: true }
      );
      console.log(
        `  Upserted "${updated.name}" (fnKey: ${updated.fnKey}, scope: ${updated.scope})`
      );
    }

    const seedFnKeys = seedNodeDefinitions.map((def) => def.fnKey);
    const removed = await NodeDefinition.deleteMany({
      fnKey: { $nin: seedFnKeys },
    });
    if (removed.deletedCount > 0) {
      console.log(`  Removed ${removed.deletedCount} obsolete definitions`);
    }

    console.log("\nSeed completed successfully");
  } catch (error) {
    console.error("Seed failed:", error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
  }
}

seed();
