name: Update Flowix API

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: [self-hosted, flowix-production]

    steps:
      - name: Update repository
        run: |
          cd ~/apps/flowix-api
          git fetch origin main
          git reset --hard origin/main